[package]
name = "bash-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.46", features = ["derive"] }
execute = "0.2.13"
tokio = { version = "1.47.1", features = ["full"] }
